on:
    push:
      tags:
        - v*
    pull_request:
      branches:
        - master

name: Create Release

jobs:
    bash-tgz:
      name: Build bash implementation
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        - name: Create tgz archive
          run: |
            mkdir remote
            cp -r bin remote
            tar -cvzf remote-sh.tgz remote
        - name: Upload release artifact
          uses: actions/upload-artifact@v2
          with:
            name: remote-sh
            path: remote-sh.tgz

    pyoxidizer-tgz:
      name: Build pyoxidizer implementation
      runs-on: macos-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        - name: Set up cargo
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install pyoxidizer
          run: cargo install pyoxidizer
        - name: Build executable and tgz
          run: |
            mkdir -p build/remote/bin
            pyoxidizer build --release
            cp build/*/release/exe/remote-exec build/remote/bin
            pip install -e .
            python scripts/setup-entrypoints.py build/remote/bin
            cd build
            tar -cvzf ../remote-pyoxidizer-macos-latest.tgz remote
        - name: Test binary is ok
          run: build/remote/bin/remote -h
        - name: Upload release artifact
          uses: actions/upload-artifact@v2
          with:
            name: remote-pyoxidizer-macos-latest
            path: remote-pyoxidizer-macos-latest.tgz

    shiv-tgz:
      name: Build shiv implementation
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.6
        - name: Install shiv
          run: pip install shiv
        - name: Build executable and tgz
          run: |
            mkdir -p build/remote/bin
            shiv -p /usr/bin/python3 -o build/remote/bin/remote-exec --no-binary :all: .
            pip install -e .
            python scripts/setup-entrypoints.py build/remote/bin --shiv
            cd build
            tar -cvzf ../remote-shiv.tgz remote
        - name: Test binary is ok
          run: build/remote/bin/remote -h
        - name: Upload release artifact
          uses: actions/upload-artifact@v2
          with:
            name: remote-shiv
            path: remote-shiv.tgz

    release:
      name: Publish release
      runs-on: ubuntu-latest
      needs:
        - bash-tgz
        - pyoxidizer-tgz
        - shiv-tgz
      if: github.event_name == 'push'
      steps:
        - name: Determine release version
          id: release_info
          env:
            TAG: ${{ github.ref }}
          run: echo "::set-output name=version::${TAG:11}"
        - name: Fetch bash artifact
          uses: actions/download-artifact@v2
          with:
            name: remote-sh
        - name: Fetch pyoxidizer macos artifact
          uses: actions/download-artifact@v2
          with:
            name: remote-pyoxidizer-macos-latest
        - name: Fetch shiv multiplatform artifact
          uses: actions/download-artifact@v2
          with:
            name: remote-shiv
        - name: Show release artifacts
          run: ls -la .
        - name: Create draft release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false
        - name: Upload bash artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./remote-sh.tgz
            asset_name: remote-${{ steps.release_info.outputs.version }}-sh.tgz
            asset_content_type: applictaion/gzip
        - name: Upload pyoxidizer macos artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./remote-pyoxidizer-macos-latest.tgz
            asset_name: remote-${{ steps.release_info.outputs.version }}-macos.tgz
            asset_content_type: applictaion/gzip
        - name: Upload shiv artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./remote-shiv.tgz
            asset_name: remote-${{ steps.release_info.outputs.version }}-shiv.tgz
            asset_content_type: applictaion/gzip
